# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne36_left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne36_right

  - board: corne42_custom
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne42_left
  - board: corne42_custom
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne42_right

  - board: corneish_zen_v2_left
    artifact-name: corneish_zen_left
  - board: corneish_zen_v2_right
    artifact-name: corneish_zen_left

  - board: eyelash_corne_left
    shield: nice_view
    artifact-name: eyelash_corne_left
  - board: eyelash_corne_right
    shield: nice_view
    artifact-name: eyelash_corne_left
    #  snippet: studio-rpc-usb-uart
    #  cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: nice_nano_v2
    shield: keyball44_left
    artifact-name: keyball44_left
  - board: nice_nano_v2
    shield: keyball44_right
    artifact-name: keyball44_right
