#define QWERTY_TL      Y_LT2          Y_LT1
#define QWERTY_TR      Y_RT1          Y_RT2
#define HARMONY_TL     Y_LT2          Y_LT1
#define HARMONY_TR     Y_RT1          Y_RT2
#define COLEMAK_TL     Y_LT2          Y_LT1
#define COLEMAK_TR     Y_RT1          Y_RT2
#define NUMBERS_TL     Y_LT2          Y_LT1
#define NUMBERS_TR     Y_RT1          Y_RT2
#define NUMPAD_TL      Y_LT2          Y_LT1
#define NUMPAD_TR      Y_RT1          Y_RT2_NP
#define SYMBOLS_TL     Y_LT2          Y_LT1
#define SYMBOLS_TR     Y_RT1          Y_RT2
#define CODING_TL      Y_LT2          Y_LT1
#define CODING_TR      Y_RT1          Y_RT2
#define NAV_TL         Y_LT2          Y_LT1
#define NAV_TR         Y_RT1          Y_RT2
#define CONTROLS_TL    Y_LT2          Y_LT1
#define CONTROLS_TR    &mkp LCLK      &mkp RCLK
#define SWITCH_TL      &out OUT_USB   &out OUT_BLE
#define SWITCH_TR      NS_A           NS_B
#define RETRO_TL       RA_MENU        &key_repeat
#define RETRO_TR       RA_TURBO       RA_PAUSE
#define PICO8_TL       PIP1_X         PIP1_O
#define PICO8_TR       PIP2_O         PIP2_X
#define MOUSE_TL       Y_LT2          Y_LT1
#define MOUSE_TR       Y_RT1          Y_RT2
#define SCROLL_TL      &trans         &trans
#define SCROLL_TR      &trans         &trans
#define SNIPE_TL       &trans         &trans
#define SNIPE_TR       &trans         &trans
#define AFK_TL         &none          &none
#define AFK_TR         &none          &none
