file_format: "1"
id: corne42_custom
name: Sofle
url: https://github.com/tokyo2006/zmk-config-corne
type: board
arch: arm
features:
  - keys
  - display
outputs:
  - usb
  - ble
siblings:
  - corne42_custom_left
  - corne42_custom_right
