draw_config:
  footer_text: ""
  key_w: 70
  key_h: 68
  split_gap: 30.0
  combo_w: 34
  combo_h: 30
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: true
  n_columns: 1
  separate_combo_diagram: false
  combo_diagrams_scale: 1
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 22
  # glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  svg_extra_style: "/* inherit to force styles through use tags */\nsvg path {\n    fill: inherit;\n}\n\n/* font and background color specifications */\nsvg.keymap {\n    font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;\n    font-size: 12px;\n    font-kerning: normal;\n    text-rendering: optimizeLegibility;\n    fill: #c1ccd9;\n}\n\n/* default key styling */\nrect.key {\n    fill: #353b40;\n    stroke: #46515c;\n    stroke-width: 2;\n}\n\n/* highlighted key styling */\nrect.hilite {\n    fill: #4d5b6d;\n    stroke: #46515c;\n    stroke-width: 2;\n}\n\n/* default key side styling, only used is draw_key_sides is set */\nrect.side {\n    filter: brightness(90%);\n}\n\n/* color accent for combo boxes */\nrect.combo, rect.combo-separate {\n    fill: #112342;\n    stroke: #404a5c;\n    stroke-width: 2px;\n}\n\n/* color accent for held keys */\nrect.held, rect.combo.held {\n    fill: #fdd;\n    stroke: #6b0d06;\n}\n\n/* color accent for LHS combos */\nrect.lhs {\n    fill: #562634;\n    stroke: #46515c;\n}\nrect.lhs-main {\n    fill: #952753;\n    stroke: #46515c;\n}\n\n/* color accent for RHS combos */\nrect.rhs {\n    fill: #1d435f;\n    stroke: #46515c;\n}\nrect.rhs-main {\n    fill: #246397;\n    stroke: #46515c;\n}\n\n/* color accent for special combo */\nrect.combo-special {\n    fill: yellow;\n    stroke: #e3af05;\n}\n\n/* color accent for combos the must include one of the keys with this same color */\nrect.combo-any {\n    fill: #81c77d;\n    stroke: #094206;\n}\n\n.combo-special, .combo-any, .held {\n    fill: #000;\n}\n\n/* color accent for ghost (optional) keys */\nrect.ghost, rect.combo.ghost {\n    stroke-dasharray: 4, 4;\n    stroke-width: 2;\n    fill: #111;\n}\n\ntext {\n    text-anchor: middle;\n    dominant-baseline: middle;\n}\n\n/* styling for layer labels */\ntext.label {\n    font-weight: bold;\n    font-size: 16px;\n    text-anchor: start;\n    stroke: white;\n    fill: #555;\n    stroke-width: 0;\n    paint-order: stroke;\n\n    display: none;\n}\n\n/* styling for combo tap, and key hold/shifted label text */\ntext.combo, text.hold, text.shifted {\n    font-size: 10px;\n    font-weight: bold;\n}\n\ntext.hold {\n    text-anchor: middle;\n    dominant-baseline: auto;\n}\n\ntext.shifted {\n    text-anchor: middle;\n    dominant-baseline: hanging;\n}\n\n/* styling for hold/shifted label text in combo box */\ntext.combo.hold, text.combo.shifted {\n    font-size: 8px;\n}\n\n/* lighter symbol for transparent keys */\ntext.trans {\n    fill: #7b7e81;\n}\n\n/* other special text colors */\n.green {\n    fill: #378b2e;\n}\n.red {\n    fill: #c62843;\n}\n.yellow {\n    fill: #eff34b;\n}\n.blue {\n    fill: #1b57c9;\n}\n\n/* styling for combo dendrons */\npath.combo {\n    stroke-width: 1;\n    stroke: gray;\n    fill: none;\n}\n\n/* Start Tabler Icons Cleanup */\n/* cannot use height/width with glyphs */\n.icon-tabler > path {\n    fill: inherit;\n    stroke: inherit;\n    stroke-width: 2;\n}\n/* hide tabler's default box */\n.icon-tabler > path[stroke=\"none\"][fill=\"none\"] {\n    visibility: hidden;\n}\n/* End Tabler Icons Cleanup */\n/* styling for layer labels */\ntext.label {\n  display: none;\n}\n"
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+ {key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
    - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
